commands = {
    'iniciar': 'void setup()',
    'loop': 'void loop()',
    'digitalEscrever': 'digitalWrite',
    'digitalLer': 'digitalRead',
    'pinoModo': 'pinMode',
    'alta': 'HIGH',
    'baixa': 'LOW',
    'saida': 'OUTPUT',
    'entrada': 'INPUT',
    'se': 'if',
    'senao': 'else',
    'para': 'for',
    'enquanto': 'while',
    'fazer': 'do',
    'caso': 'switch',
    'casoDe': 'case',
    'quebrar': 'break',
    'continuar': 'continue',
    'retornar': 'return',
    'constante': 'const',
    'variavel': 'int',
    'flutuante': 'float',
    'caracter': 'char',
    'longo': 'long',
    'dobro': 'double',
    'semSinal': 'unsigned',
    'verdadeiro': 'true',
    'falso': 'false',
    'nada': 'void',
    'inteiro': 'int',
    'flutuante': 'float',
    'paraCada': 'for each',
    'pausar': 'delay',
    'tempoAtual': 'millis',
    'pinoAnalogicoLer': 'analogRead',
    'pinoAnalogicoEscrever': 'analogWrite',
    'aleatorio': 'random',
    'aleatorioSeed': 'randomSeed',
    'mapear': 'map',
    'conexaoSerial': 'Serial.begin',
    'imprimirSerial': 'Serial.print',
    'imprimirLinhaSerial': 'Serial.println',
    'disponivelSerial': 'Serial.available',
    'lerSerial': 'Serial.read',
    'escreverSerial': 'Serial.write',
    'anexarInterrupcao': 'attachInterrupt',
    'desanexarInterrupcao': 'detachInterrupt',
    'inicioTons': 'tone',
    'pararTons': 'noTone',
    'lerPulso': 'pulseIn',
    'tempoPassado': 'micros'
}